### ISSUE TITLE
How do I not make it be the first thing that pops up when i run the app?

### ISSUE THREAD

**Issue by ghost** [wanaya/Slide-Menu#2]
I have my login system that i want to be the first thing that comes when i run the app. 
I'm the sure it's the code in the app delegate, in didFinishLaunchingWithOptions. 

How do i modify it, so the menu slider is only shown when the user has logged in and reached the appropriate viewcontroller for it?

**Comment by wanaya** [comment]
after you logged in in you system, you need to replace the rootViewController of you app to the navigationController in this rep.

 let nav: UIViewController = NavViewController() 
 let navigationController = UINavigationController(rootViewController: nav)
let appDelegate  = UIApplication.sharedApplication().delegate as AppDelegate
appDelegate.window!.rootViewController = navigationController

This is one way, other way you cant disable de gestures and the top buttons until you get logged in.
